#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
STEP 06 - Train / validation / test split (paper Sec. 4.1: 80 % / 10 % / 10 %).

Input : out/images, out/labels, out/manifest.csv
Output: out/train.txt, out/val.txt, out/test.txt   image paths relative to out/
        out/dataset.yaml                            Ultralytics dataset file

The split is done per BACKGROUND (all variants generated from the same
aerial shot land in the same subset), so validation/test images never share
a background with training images. Use --by-image for a plain random split.
"""

import argparse
import random
from collections import defaultdict

import config as C
from pipeline_utils import read_csv


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--train", type=float, default=0.8)
    ap.add_argument("--val", type=float, default=0.1)
    ap.add_argument("--seed", type=int, default=C.SEED)
    ap.add_argument("--by-image", action="store_true", help="ignore background grouping")
    args = ap.parse_args()

    rows = read_csv(C.OUT_MANIFEST)
    if not rows:
        raise SystemExit("out/manifest.csv not found - run 05-combine.py first")
    random.seed(args.seed)

    groups = defaultdict(list)
    for r in rows:
        groups[r["image"] if args.by_image else r["background"]].append(r["image"])
    keys = sorted(groups)
    random.shuffle(keys)

    n = len(keys)
    n_train, n_val = int(n * args.train), int(n * args.val)
    parts = {"train": keys[:n_train], "val": keys[n_train:n_train + n_val], "test": keys[n_train + n_val:]}

    for name, ks in parts.items():
        files = sorted(img for k in ks for img in groups[k])
        # "./images/x.jpg" is resolved by Ultralytics relative to the txt file,
        # so the dataset folder can be moved / cloned anywhere
        (C.OUT_DIR / f"{name}.txt").write_text(
            "\n".join(f"./images/{f}" for f in files) + "\n", encoding="utf-8")
        print(f"{name:5s} {len(ks):5d} groups  {len(files):6d} images")

    # no "path:" key on purpose: Ultralytics then uses the yaml's own folder
    C.OUT_YAML.write_text(
        f"# generated by 06-split.py - portable, resolved relative to this file\n"
        f"train: train.txt\nval: val.txt\ntest: test.txt\n"
        f"nc: {len(C.CLASS_NAMES)}\nnames: {C.CLASS_NAMES}\n", encoding="utf-8")
    print(f"Dataset yaml: {C.OUT_YAML}")


if __name__ == "__main__":
    main()
